language: cpp
sudo: false
compiler:
  - gcc
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab3-postfix/
  - make -j
  - cd ./test/
  - ls -la
  - ./postfix_test
notifications:
  email: false
